# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-27 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(max_length=8, null=True),
        ),
    ]
