# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-28 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20170727_2148'),
        ('second_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poke',
            name='user_id',
        ),
        migrations.AddField(
            model_name='poke',
            name='poke',
            field=models.ManyToManyField(related_name='poke', to='first_app.User'),
        ),
    ]
